version: 0.2

phases:
  build:
    commands:
      - yarn
      - yarn build
  post_build:
    commands:
      - ls -l
      - mv dist/* ./
artifacts:
  files:
    - client/index.html
    - package.json
    - server.js
    - data.js
    - interfaces.js
